services:
    nginx:
        image: nginx:alpine
        container_name: kcs-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./ssl:/etc/nginx/ssl # SSL certificates volume
        depends_on:
            - api
            - redis
        restart: always
        networks:
            - kcs-network

    api:
        build:
            context: .
            dockerfile: ${DOCKERFILE:-Dockerfile}
        container_name: kcs-api
        ports:
            - "4500:4500" # HTTP API
            - "4501:4501" # Socket.IO WebSocket
            - "40000-40100:40000-40100/udp" # MediaSoup RTC ports
            - "40000-40100:40000-40100/tcp" # MediaSoup RTC ports
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - REDIS_URL=redis://redis:6379
            - MEDIASOUP_LISTEN_IP=0.0.0.0
            - MEDIASOUP_ANNOUNCED_IP=${MEDIASOUP_ANNOUNCED_IP:-127.0.0.1}
            - SOCKET_IO_PORT=4501
        depends_on:
            - redis
        restart: always
        networks:
            - kcs-network
        volumes:
            - ./logs:/app/logs
            - ./uploads:/app/uploads
            - ./recordings:/app/recordings
        deploy:
            resources:
                limits:
                    memory: 2G
                    cpus: "1.5"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4500/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    redis:
        image: redis:7-alpine
        container_name: kcs-redis
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
        volumes:
            - redis-data:/data
        restart: always
        networks:
            - kcs-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 5s
            retries: 3

volumes:
    redis-data:
        driver: local

networks:
    kcs-network:
        driver: bridge
