import { z } from "zod";

export const actionMap: {
    [key: string]: string[];
} = {
    Student: [
        "get_user",
        "get_class",
        "get_all_courses",
        "get_course",
        "get_subject",
        "get_exam",
        "student_get_assignments",
        "student_get_assignment",
        "student_submit_assignment",
        "student_assignment_dashboard",
        "student_assignment_performance",
        "get_assignment",
        // Course content permissions
        "view_course_content",
        "view_course_materials",
        "track_watch_history",
        "view_course_progress",
        "download_materials",
    ],
    Parent: [
        "get_user",
        "parent_get_student_assignments",
        "parent_get_student_performance",
    ],
    Teacher: [
        "get_user", 
        "get_users",
        "create_assignment",
        "update_assignment",
        "delete_assignment",
        "get_assignment",
        "teacher_get_assignments",
        "teacher_get_submissions",
        "teacher_grade_submission",
        "teacher_assignment_dashboard",
        // Course content permissions
        "create_course_content",
        "update_course_content",
        "delete_course_content",
        "create_course_chapter",
        "update_course_chapter",
        "create_course_folder",
        "upload_course_materials",
        "manage_course_materials",
        "view_course_analytics",
        "create_lesson_steps",
        "bulk_upload_materials",
    ],
    Staff: [
        "get_user",
        "get_users",
        "create_users",
        "update_users",
        "delete_users",
        "get_assignment",
    ],
    Principal: [
        "get_user",
        "get_users",
        "create_users",
        "update_users",
        "delete_users",
        "create_assignment",
        "update_assignment",
        "delete_assignment",
        "get_assignment",
        "admin_assignment_overview",
        "admin_assignment_analytics",
        "admin_bulk_assignment_operations",
    ],
    Admin: [
        "get_user",
        "get_users",
        "create_users",
        "update_users",
        "delete_users",
        "create_campus",
        "get_all_campus",
        "get_campus",
        "update_campus",
        "delete_campus",
        "create_class",
        "get_all_class",
        "get_class",
        "update_class",
        "delete_class",
        "create_subject",
        "get_all_subject",
        "get_subject",
        "update_subject",
        "delete_subject",
        "create_assignment",
        "update_assignment",
        "delete_assignment",
        "get_assignment",
        "admin_assignment_overview",
        "admin_assignment_analytics",
        "admin_bulk_assignment_operations",
        // Course content permissions (full access)
        "create_course_content",
        "update_course_content",
        "delete_course_content",
        "create_course_chapter",
        "update_course_chapter",
        "delete_course_chapter",
        "create_course_folder",
        "update_course_folder",
        "delete_course_folder",
        "upload_course_materials",
        "manage_course_materials",
        "delete_course_materials",
        "view_course_analytics",
        "manage_course_analytics",
        "create_lesson_steps",
        "bulk_upload_materials",
        "manage_course_permissions",
    ],
    "Super Admin": [
        "create_campus",
        "get_all_campus",
        "get_campus",
        "update_campus",
        "delete_campus",
        "create_users",
    ],
    Public: [],
};

// use zod to create a union type for action names
const actionNameSchema = z.union([
    z.literal("get_user"),
    z.literal("get_users"),
    z.literal("create_users"),
    z.literal("update_users"),
    z.literal("delete_users"),
    z.literal("create_campus"),
    z.literal("get_all_campus"),
    z.literal("get_campus"),
    z.literal("update_campus"),
    z.literal("delete_campus"),
    z.literal("create_class"),
    z.literal("get_all_class"),
    z.literal("get_class"),
    z.literal("update_class"),
    z.literal("delete_class"),
    z.literal("create_subject"),
    z.literal("get_all_subject"),
    z.literal("get_subject"),
    z.literal("update_subject"),
    z.literal("delete_subject"),
    // Assignment actions
    z.literal("create_assignment"),
    z.literal("update_assignment"),
    z.literal("delete_assignment"),
    z.literal("get_assignment"),
    // Admin assignment actions
    z.literal("admin_assignment_overview"),
    z.literal("admin_assignment_analytics"),
    z.literal("admin_bulk_assignment_operations"),
    // Teacher assignment actions
    z.literal("teacher_get_assignments"),
    z.literal("teacher_get_submissions"),
    z.literal("teacher_grade_submission"),
    z.literal("teacher_assignment_dashboard"),
    // Student assignment actions
    z.literal("student_get_assignments"),
    z.literal("student_get_assignment"),
    z.literal("student_submit_assignment"),
    z.literal("student_assignment_dashboard"),
    z.literal("student_assignment_performance"),
    // Parent assignment actions
    z.literal("parent_get_student_assignments"),
    z.literal("parent_get_student_performance"),
    // Course content management actions
    z.literal("view_course_content"),
    z.literal("view_course_materials"),
    z.literal("track_watch_history"),
    z.literal("view_course_progress"),
    z.literal("download_materials"),
    z.literal("create_course_content"),
    z.literal("update_course_content"),
    z.literal("delete_course_content"),
    z.literal("create_course_chapter"),
    z.literal("update_course_chapter"),
    z.literal("delete_course_chapter"),
    z.literal("create_course_folder"),
    z.literal("update_course_folder"),
    z.literal("delete_course_folder"),
    z.literal("upload_course_materials"),
    z.literal("manage_course_materials"),
    z.literal("delete_course_materials"),
    z.literal("view_course_analytics"),
    z.literal("manage_course_analytics"),
    z.literal("create_lesson_steps"),
    z.literal("bulk_upload_materials"),
    z.literal("manage_course_permissions"),
]);

export type ActionType = z.infer<typeof actionNameSchema>;
